spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://udo0zjg4f0rnrssl:sZnfCzwYM81t645OykJq@beylta3fkdfkqojjsui1-mysql.services.clever-cloud.com:3306/beylta3fkdfkqojjsui1

    password: "root"
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      name: "udo0zjg4f0rnrssl"
      password: "sZnfCzwYM81t645OykJq"
        
thymeleaf:
  cache: false
server:
  port: '8080'
 
